# Generated by Django 5.0 on 2024-03-27 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appeal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appeal',
            name='datecruise',
        ),
    ]
