# Generated by Django 5.0.4 on 2024-04-06 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeal', '0002_remove_appeal_datecruise'),
        ('cruise_list', '0003_cruise_delete_сruise'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appeal',
            name='type',
        ),
        migrations.AddField(
            model_name='appeal',
            name='cruise',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='cruise_list.cruise'),
        ),
        migrations.AddField(
            model_name='appeal',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to=settings.AUTH_USER_MODEL),
        ),
    ]
