# Generated by Django 5.0.4 on 2024-04-08 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeal', '0004_alter_appeal_status_alter_appeal_uid'),
        ('cruise_list', '0006_alter_cruise_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='cruise',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='cruise_list.cruise', verbose_name='Круиз'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
