# Generated by Django 5.0.4 on 2024-04-08 00:11

import users.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_token',
            field=models.CharField(default=users.utils.random_token_generator, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_room_category',
            field=models.CharField(choices=[('inside', 'Внутренний'), ('oceanview', 'С окном'), ('balcony', 'С балконом'), ('suite', 'Люкс')], default=None, max_length=10, null=True, verbose_name='Предпочитаемая категория кают'),
        ),
    ]
