# Generated by Django 5.0.4 on 2024-04-08 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_email_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preferred_room_price_max',
            field=models.PositiveIntegerField(default=None, null=True, verbose_name='Предпочитаемая цена до'),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_room_price_min',
            field=models.PositiveIntegerField(default=None, null=True, verbose_name='Предпочитаемая цена от'),
        ),
    ]
