# Generated by Django 5.0 on 2024-03-27 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruise_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='сruise',
            name='discription',
            field=models.TextField(default=2, verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
