# Generated by Django 5.0.4 on 2024-04-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruise_list', '0002_áruise_discription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cruise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
                ('time', models.CharField(max_length=60, verbose_name='Время круиза')),
                ('cities', models.CharField(max_length=128, verbose_name='Название городов')),
                ('discription', models.TextField(verbose_name='Описание')),
                ('price', models.CharField(max_length=100, verbose_name='Стоимость')),
                ('publish_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата публикации')),
                ('edit_date', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата редактирования')),
                ('image', models.ImageField(blank=True, null=True, upload_to='%Y/%m/%d')),
                ('view', models.CharField(max_length=128, verbose_name='Просмотры')),
            ],
            options={
                'verbose_name': 'Маршруты и корабли',
                'verbose_name_plural': 'Маршруты и корабли',
                'ordering': ('-publish_date', '-edit_date'),
            },
        ),
        migrations.DeleteModel(
            name='Сruise',
        ),
    ]
