# Generated by Django 5.0.4 on 2024-04-07 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruise_list', '0003_cruise_delete_сruise'),
    ]

    operations = [
        migrations.AddField(
            model_name='cruise',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Активен'),
        ),
    ]
