# Generated by Django 5.0.4 on 2024-04-08 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruise_list', '0004_cruise_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cruise',
            name='price',
            field=models.CharField(max_length=100, verbose_name='Рекламная цена'),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('inside', 'Внутренний'), ('oceanview', 'С окном'), ('balcony', 'С балконом'), ('suite', 'Люкс')], default=None, max_length=10, verbose_name='Категория')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='количество мест')),
                ('cruise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staterooms', to='cruise_list.cruise')),
            ],
            options={
                'verbose_name': 'Категория кают',
                'verbose_name_plural': 'Кактегории кают',
                'ordering': ('cruise', 'category'),
            },
        ),
    ]
