# Generated by Django 5.0.4 on 2024-04-08 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruise_list', '0005_alter_cruise_price_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cruise',
            name='price',
            field=models.CharField(max_length=100, verbose_name='Цена'),
        ),
    ]
