# Generated by Django 5.0.4 on 2024-04-08 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruise_list', '0006_alter_cruise_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='cruise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='cruise_list.cruise'),
        ),
    ]
